In [1]:
import pandas as pd

customers = pd.read_csv("customers.csv")
tickets = pd.read_csv("tickets.csv")
labels = pd.read_csv("labels.csv")

In [2]:
print(customers.columns)
print(tickets.columns)
print(labels.columns)

Index(['ticket_id', 'customer_region', 'account_type'], dtype='object')
Index(['ticket_id', 'ticket_text', 'customer_tenure_months',
       'previous_tickets_count'],
      dtype='object')
Index(['ticket_id', 'department', 'priority'], dtype='object')

In [4]:
df = tickets.merge(customers, on="ticket_id", how="left") \
            .merge(labels, on="ticket_id", how="left")

In [5]:
df

,ticket_id,ticket_text,customer_tenure_months,previous_tickets_count,customer_region,account_type,department,priority
0,TKT00000,I have suggestions to improve the usability of...,20,2,India,Premium,Product Feedback,Low
1,TKT00001,I have suggestions to improve the usability of...,37,1,US,Free,Product Feedback,Medium
2,TKT00002,I would like more information about pricing an...,18,2,India,Free,Sales,Medium
3,TKT00003,The application crashes frequently and shows u...,8,1,Canada,Free,Technical Support,Low
4,TKT00004,The application crashes frequently and shows u...,23,1,UK,Free,Technical Support,Low
...,...,...,...,...,...,...,...,...
2995,TKT02995,I would like more information about pricing an...,5,0,India,Free,Sales,Low
2996,TKT02996,I was charged incorrectly and need clarificati...,42,1,India,Premium,Billing,Low
2997,TKT02997,The application crashes frequently and shows u...,29,2,India,Free,Technical Support,Low
2998,TKT02998,I would like more information about pricing an...,26,1,UK,Free,Sales,Low
2999,TKT02999,I need assistance updating my account details ...,52,1,UK,Free,Account Management,High

In [6]:
X = df.drop(["ticket_id", "department", "priority"], axis=1)
y = df["department"]

X = pd.get_dummies(X, columns=["customer_region", "account_type"], drop_first=True)

In [8]:
X.head()

,ticket_text,customer_tenure_months,previous_tickets_count,customer_region_India,customer_region_UK,customer_region_US,account_type_Free,account_type_Premium
0,I have suggestions to improve the usability of...,20,2,True,False,False,False,True
1,I have suggestions to improve the usability of...,37,1,False,False,True,True,False
2,I would like more information about pricing an...,18,2,True,False,False,True,False
3,The application crashes frequently and shows u...,8,1,False,False,False,True,False
4,The application crashes frequently and shows u...,23,1,False,True,False,True,False

In [9]:
y.head()

0     Product Feedback
1     Product Feedback
2                Sales
3    Technical Support
4    Technical Support
Name: department, dtype: object